train_data_path: data/full_train.csv
dev_data_path: data/full_dev.csv

store_fmt: onehot
dayofweek_fmt: periodic
date_fmt: periodic
noise_size: 0.05

latent_dim: 256
g_hdims:
  - 2048
d_hdims:
  - 2048

g_lr: 1.0E-4
g_beta1: 0.5
g_beta2: 0.999

d_lr: 3.0E-5
d_beta1: 0.5
d_beta2: 0.999

epochs: 6
batch_size: 256
running_avg_size: 40
train_tracking_period: 200

model_dir: models
log_dir: models