train_data_path: ds_test/tiny_train.csv
dev_data_path: ds_test/tiny_dev.csv

store_fmt: onehot
dayofweek_fmt: periodic
date_fmt: periodic
noise_size: 0.05

latent_dim: 32
g_hdims:
  - 128
d_hdims:
  - 128

g_lr: 1.0E-3
g_beta1: 0.5
g_beta2: 0.999

d_lr: 1.0E-3
d_beta1: 0.5
d_beta2: 0.999

epochs: 1
batch_size: 512
running_avg_size: 5
train_tracking_period: 20

model_dir: models
log_dir: models